name: "Deploy node application"
description: "Composite action to deploy and build out node app"
inputs:
  environment:
    description: "Environment where to deploy Sample Book Application"
    required: true
  port:
    description: "Port for our Sample Book Application"
    required: true
runs:
  using: composite
  steps:
    - name: Print step name
      run: echo "Deployment to ${{ inputs.environment }} has started.."
      shell: cmd
    - name: Install all dependencies
      run: npm install
      shell: cmd
    - name: Delete existing pm2 service
      run: pm2 delete "books-${{ inputs.environment }}"
      shell: cmd
    - name: Run sample-book-app pm2 service
#     run: $env:PORT=${{ inputs.port }}; pm2 start -n "books-${{ inputs.environment }}" index.js
      run: pm2 start -n "books-${{ inputs.environment }}" index.js -- ${{ inputs.port }}
      shell: cmd